name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  repro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: corepack enable

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-pnpm-  

      - run: pnpm i

      - run: 'for i in {1..12}; do AMOUNT="$i" pnpm rspack build --mode production; done'
        env:
          NODE_ENV: production
